name: frontend
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5-114.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  retrofit: ^4.0.0
  dio: ^5.0.0
  provider: '>=5.0.2'
  lottie:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  json_annotation: ^4.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/